    
    %=================================================================
    %=================================================================

    % Code associated to the work submitted to the VSS'24 conference
    
    % (c) [2024]  Nantes Université - Centrale Nantes - LS2N UMR 6004, Nantes
    % (c) [2024]  Quartz EA 7393, ENSEA, Cergy-Pontoise
    % Loïc MICHEL, Malek GHANES, Yannick AOUSTIN and Jean-Pierre BARBOT
    % All rights reserved under MIT license.

    %=================================================================
    %=================================================================
    
    if (caseNumber == 0)
        delete Result_error_evaluation.txt
        delete 'Result_error_evaluation_latex.txt'
    end
    
    caseNumber = caseNumber + 1; % Update index of figures

    fprintf('\n\n\n ************************************************************ \n');
    fprintf(name);
    fprintf('\n************************************************************ \n\n\n');
    
    ImplicitDifferentiator ( TMax , ...
        Deltah , ...
        NoiseAmp , ...
        PresetInputKnowledge , ...
        ForceThetaZero , ...
        cascade_diff , ...
        mono_diff , ...
        u , ...
        P , ...
        c_alpha_1_1 , ...
        c_alpha_1_2 , ...
        c_lambda_1_1 , ...
        c_lambda_2_1 , ...
        c_lambda_1_2 , ...
        c_lambda_2_2 , ...
        c_theta_1 , ...
        c_theta_2 , ...
        c_theta_3 , ...
        c_theta_4 , ...
        c_lambda_fwd , ...
        m_alpha_1 , ...
        m_alpha_2 , ...
        m_alpha_3 , ...
        m_alpha_4 , ...
        m_lambda_1, ...
        m_lambda_2 , ...
        m_lambda_3 , ...
        m_lambda_4 , ...
        m_theta_1 , ...
        m_theta_2 , ...
        m_theta_3 , ...
        m_theta_4 , ...
        xIC , ...
        m_correction_factor , ...
        c_MU_ , ...
        c_correction_factor , ...
        name , ...
        caseNumber);
    
    fprintf("End of the case... \n");
    
    
    

